[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
remappings = ['@openzeppelin/=lib/openzeppelin-contracts/']

[rpc_endpoints]
scroll_testnet = "https://sepolia-rpc.scroll.io/"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
